export const environment = {
    BASE_ALBUM_URL: "http://localhost:3000/api/albums",
    BASE_USER_URL: "http://localhost:3000/api/users",
    LOCAL_STORAGE_IS_LOGGED: "isLogged",
    LOCAL_STORAGE_USER: "user",
    LOCAL_STORAGE_TOKEN: "token",
    LOCAL_STORAGE_TRUE_VALUE: "true",
    LOCAL_STORAGE_EMPTY_PAYLOAD_VALUE: "{}",
    LOCAL_STORAGE_EMPTY_STRING_VALUE: "",
    HOME: "Home",
    ALBUM: "Album",
    ADD_ALBUM: "Add Album",
    SHOW_ALBUM: "Show Albums",
    PROFILE: "Profile",
    REGISTER: "Register",
    LOGOUT: "Logout",
    LOGIN: "Login",
    LOGIN_SUCCESS: "Log in Successfully",
    LOGIN_FAIL: "Log in failed",
    AUTHORIZATION: "Authorization",
    PREVIOUS: "Previous",
    NEXT: "Next",
    ADD_SONG: "Add Song",
    TITLE: "Title",
    LENGTH: "Length",
    ACTIONS: "Actions",
    EDIT: "Edit",
    DELETE: "Delete",
    DETAIL: "Detail",
    HOME_TITLE: "Welcome to my albums",
    YEAR: "Year",
    IMAGE: "Image",
    NAME: "Name",
    GENDER: "Gender",
    USERNAME: "Username",
    PASSWORD: "Password",
    RETYPE_PASSWORD: "Re-type password",
    INVALID_USERNAME_PASSWORD: "Username and password is required",
    INVALID_RETYPE_PASSWORD: "Password must be match",
    REGISTER_FAILED: "Register failed"
};
