const STATUS_SERVER_ERROR = 500;

const STATUS_BAD_REQUEST = 400;

const STATUS_NOT_FOUND = 404;
const STATUS_UNAUTHORIZED = 401;

const STATUS_OK = 200;

const STATUS_CREATED = 201;

module.exports = {
    STATUS_BAD_REQUEST,
    STATUS_CREATED,
    STATUS_OK,
    STATUS_SERVER_ERROR,
    STATUS_NOT_FOUND,
    STATUS_UNAUTHORIZED
}